# Generated by Django 3.1.4 on 2020-12-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_auto_20201226_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='username',
            new_name='user_id',
        ),
    ]
