# Generated by Django 3.1.4 on 2021-01-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_auto_20201226_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='uid',
        ),
    ]
